apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
  # annotations:
  #   "helm.sh/hook": pre-install,pre-upgrade, post-delete
  #   "helm.sh/hook-weight": "2"
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
            - name: test-volume
              mountPath: /test
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: test-volume
          persistentVolumeClaim:
            claimName: stress-test-volumeclaim
