apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stress-test-volumeclaim-cc
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.stressTestVolumeclaim.storageSize }}
  storageClassName: {{ .Values.stressTestVolumeclaim.storageClassName }}
